/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : pin_mux.c
**     Project     : twrk22f120m
**     Processor   : MK22FN512VMC12
**     Component   : PinSettings
**     Version     : Component 01.002, Driver 1.1, CPU db: 3.00.000
**     Compiler    : IAR ARM C Compiler
**     Date/Time   : 2013-12-10, 14:58, # CodeGen: 7
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         CAN                 - void pin_mux_CAN(uint32_t instance);
**         ENET                - void pin_mux_ENET(uint32_t instance);
**         GPIO                - void pin_mux_GPIO(uint32_t instance);
**         I2C                 - void pin_mux_I2C(uint32_t instance);
**         RTC                 - void pin_mux_RTC(uint32_t instance);
**         SDHC                - void pin_mux_SDHC(uint32_t instance);
**         SPI                 - void pin_mux_SPI(uint32_t instance);
**         UART                - void pin_mux_UART(uint32_t instance);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.1
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

/* MODULE pin_mux. */

#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "pin_mux.h"
#include "sat_module.h"


void pin_mux_GPIO(uint32_t instance)
{
  switch(instance) {    
    case PORTA_IDX:                             /* PTA */
#if PROTO_BOARD
      /* PTA4 - LED RED */
      PORT_HAL_SetMuxMode(PORTA,4u,kPortMuxAsGpio);
      /* PTA5 - LED GREEN */
      PORT_HAL_SetMuxMode(PORTA,5u,kPortMuxAsGpio);
      /* PTA12 - LED BLUE */
      PORT_HAL_SetMuxMode(PORTA,12u,kPortMuxAsGpio);
#else
      /* PTA12 - LED RED */
      PORT_HAL_SetMuxMode(PORTA,12u,kPortMuxAsGpio);
      /* PTA13 - LED GREEN */
      PORT_HAL_SetMuxMode(PORTA,13u,kPortMuxAsGpio);
      /* PTA14 - LED BLUE */
      PORT_HAL_SetMuxMode(PORTA,14u,kPortMuxAsGpio);
#endif
      break;
    case PORTB_IDX:                             /* PTB */
#if PROTO_BOARD
      /* PORTB_PCR0 */
      PORT_HAL_SetMuxMode(PORTB,0u,kPortMuxAsGpio);
      /* PORTB_PCR1 */
      PORT_HAL_SetMuxMode(PORTB,1u,kPortMuxAsGpio);
      /* PORTB_PCR2 */
      PORT_HAL_SetMuxMode(PORTB,2u,kPortMuxAsGpio);
#else
      /* PTB7 - nRT51 P0.18 */
      PORT_HAL_SetMuxMode(PORTB,7u,kPortMuxAsGpio);
      /* PTB8 - nRT51 P0.17 */
      PORT_HAL_SetMuxMode(PORTB,8u,kPortMuxAsGpio);
      /* PTB9 - nRT51 P0.19 */
      PORT_HAL_SetMuxMode(PORTB,9u,kPortMuxAsGpio);
      /* PTB18 - nRT51 SWDCLK */
      PORT_HAL_SetMuxMode(PORTB,18u,kPortMuxAsGpio);
      /* PTB19 - nRT51 SWDIO/nRST */
      PORT_HAL_SetMuxMode(PORTB,19u,kPortMuxAsGpio);
#endif
      break;
    case PORTC_IDX:                             /* PTC */
#if PROTO_BOARD
      /* PORTC_PCR0 */
      PORT_HAL_SetMuxMode(PORTC,0u,kPortMuxAsGpio);
      /* PORTC_PCR1 */
      PORT_HAL_SetMuxMode(PORTC,1u,kPortMuxAsGpio);
      /* PORTC_PCR3 */
      PORT_HAL_SetMuxMode(PORTC,3u,kPortMuxAsGpio);
#else
      /* PTC8 - MPU9250 INT */
      PORT_HAL_SetMuxMode(PORTC,8u,kPortMuxAsGpio);
      /* PTC9 - MPU9250 FSYNC */
      PORT_HAL_SetMuxMode(PORTC,9u,kPortMuxAsGpio);
#endif
//      /* PORTC_PCR4 */
//      PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAsGpio);
//      /* PORTC_PCR7 */
//      PORT_HAL_SetMuxMode(PORTC,7u,kPortMuxAsGpio);
//      /* PORTC_PCR11 */
//      PORT_HAL_SetMuxMode(PORTC,11u,kPortMuxAsGpio);
      break;
    case PORTD_IDX:
      /* PORTD_PCR2 */
      PORT_HAL_SetMuxMode(PORTD,2u,kPortMuxAsGpio);
      /* PORTD_PCR3 */
      PORT_HAL_SetMuxMode(PORTD,3u,kPortMuxAsGpio);
      break;
    case PORTE_IDX:                             /* PTE */
      /* PORTE_PCR0 */
      PORT_HAL_SetMuxMode(PORTE,0u,kPortMuxAsGpio);
      /* PORTE_PCR1 */
      PORT_HAL_SetMuxMode(PORTE,1u,kPortMuxAsGpio);
      break;
    default:
      break;
  }
}

void pin_mux_I2C(uint32_t instance)
{
  switch(instance) {    
    case 0:                             /* I2C0 */
      /* PORTB_PCR2 */
      PORT_HAL_SetMuxMode(PORTB,2u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTB,2u,true);
      /* PORTB_PCR3 */
      PORT_HAL_SetMuxMode(PORTB,3u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTB,3u,true);
      break;
    case 1:                             /* I2C1 */
      /* PORTC_PCR10 */
      PORT_HAL_SetMuxMode(PORTC,10u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,10u,true);
      /* PORTC_PCR11 */
      PORT_HAL_SetMuxMode(PORTC,11u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,11u,true);
      break;
    default:
      break;
  }
}

void pin_mux_RTC(uint32_t instance)
{
  /* PORTE_PCR26 */
  PORT_HAL_SetMuxMode(PORTE,0u,kPortMuxAlt7);
}

void pin_mux_SPI(uint32_t instance)
{
#if PROTO_BOARD
  // Prototype Sensor Module
  switch(instance) {
	case 0:   // SPI0 for Nordic nRF51822
	  // PTC4 - SPI0_nCS0
	  PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAlt2);
	  // PTC5 - SPI0_SCLK
	  PORT_HAL_SetMuxMode(PORTC,5u,kPortMuxAlt2);
	  // PTC6 - SPI0_SOUT
	  PORT_HAL_SetMuxMode(PORTC,6u,kPortMuxAlt2);
	  // PTC7 - SPI0_SIN
	  PORT_HAL_SetMuxMode(PORTC,7u,kPortMuxAlt2);
	  break;
    case 1:   /* SPI1 for Invensense MPU9250 */
	  /* PTD4 - SPI1_nCS0 */
	  PORT_HAL_SetMuxMode(PORTD,4u,kPortMuxAlt7);
	  /* PTD5 - SPI1_SCLK */
	  PORT_HAL_SetMuxMode(PORTD,5u,kPortMuxAlt7);
	  /* PTD6 - SPI1_MOSI */
	  PORT_HAL_SetMuxMode(PORTD,6u,kPortMuxAlt7);
	  /* PTD7 - SPI1_MISO */
	  PORT_HAL_SetMuxMode(PORTD,7u,kPortMuxAlt7);
	  break;
    default:
      break;
  }
#else
  // Production Sensor Module
  switch(instance) {
	case 0:   // SPI0 for Invensense MPU9250
	  // PTC4 - SPI0_nCS0
	  PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAlt2);
	  // PTC5 - SPI0_SCLK
	  PORT_HAL_SetMuxMode(PORTC,5u,kPortMuxAlt2);
	  // PTC6 - SPI0_SOUT
	  PORT_HAL_SetMuxMode(PORTC,6u,kPortMuxAlt2);
	  // PTC7 - SPI0_SIN
	  PORT_HAL_SetMuxMode(PORTC,7u,kPortMuxAlt2);
	  break;
    case 1:   // SPI1 for Nordic nRF51822
	  /* PTB10 - SPI1_nCS0 */
	  PORT_HAL_SetMuxMode(PORTB,10u,kPortMuxAlt2);
	  /* PTB11 - SPI1_SCLK */
	  PORT_HAL_SetMuxMode(PORTB,11u,kPortMuxAlt2);
	  /* PTB16 - SPI1_SOUT */
	  PORT_HAL_SetMuxMode(PORTB,16u,kPortMuxAlt2);
	  /* PTB17 - SPI1_SIN */
	  PORT_HAL_SetMuxMode(PORTB,17u,kPortMuxAlt2);
	  break;
    default:
      break;
  }
#endif
}

void pin_mux_UART(uint32_t instance)
{
  switch(instance) {
    case 1:                             /* UART1 BT */
      /* PORTE_PCR0 */
      PORT_HAL_SetMuxMode(PORTE,0u,kPortMuxAlt3);
      /* PORTE_PCR1 */
      PORT_HAL_SetMuxMode(PORTE,1u,kPortMuxAlt3);
      break;
    default:
      break;
  }
}

void pin_mux_I2S(uint32_t instance)
{
  /* MCLK output */
  PORT_HAL_SetMuxMode(PORTC,8u,kPortMuxAlt4);
  /* RX Data */
  PORT_HAL_SetMuxMode(PORTC,5u,kPortMuxAlt4);
  /* RX Frame Sync */
  PORT_HAL_SetMuxMode(PORTC,7u,kPortMuxAlt4);
  /* RX Bit clock */
  PORT_HAL_SetMuxMode(PORTC,9u,kPortMuxAlt4);
  /* TX Bit Clock */
  PORT_HAL_SetMuxMode(PORTA,5u,kPortMuxAlt6);
  /* TX Frame Sync */
  PORT_HAL_SetMuxMode(PORTA,13u,kPortMuxAlt6);
  /* TX Data */
  PORT_HAL_SetMuxMode(PORTA,12u,kPortMuxAlt6);
}

/* UNUSED
void pin_mux_SPI_CS0(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD,0u,kPortMuxAsGpio);
}

void pin_mux_SPI_CS1(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTD,4u,kPortMuxAsGpio);
}
*/

void pin_mux_FTM(uint32_t instance)
{
    switch(instance) 
    {    
        case 0:
            PORT_HAL_SetMuxMode(PORTD,5u,kPortMuxAlt4);
            break;
        default:
            break;
    }
}

void pin_mux_GPIO_I2C(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTB,2u,kPortMuxAsGpio);
  PORT_HAL_SetOpenDrainCmd(PORTB,2u,true);
  PORT_HAL_SetMuxMode(PORTB,3u,kPortMuxAsGpio);
  PORT_HAL_SetOpenDrainCmd(PORTB,3u,true);
}

void pin_mux_GPIO_UART(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTE,0u,kPortMuxAsGpio);
  PORT_HAL_SetMuxMode(PORTE,1u,kPortMuxAsGpio);
}


void pin_mux_PTA5_alt2(void) {
    PORT_HAL_SetMuxMode(PORTA,5u,kPortMuxAlt2);
}

void pin_mux_PTA5_gpio(void) {
    PORT_HAL_SetMuxMode(PORTA,5u,kPortMuxAsGpio);
}
/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
